manifest_version = 2
name = "Fanout starter for Rust"
description = "Implements Fanout handlers for WebSockets, SSE, etc."
authors = ["<oss@fastly.com>"]
language = "rust"
service_id = "0S3yhq7NCuUzPYAfulMyWZ"
